spring.application.name=Celonis_Service
#spring.datasource.url=jdbc:postgresql://localhost:5432/celonis_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

server.port=8082


## H2 Console ? access at http://localhost:8080/h2-console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin123

#
#product-api: https://dummyjson.com/products/1
#log-success-url: http://localhost:8082/logs
#log-error-url: http://localhost:8082/logs

camunda.bpm:
history-level: full
auto-deployment-enabled: true




spring:
elasticsearch:
uris: http://localhost:9200   
username: elastic             
password: changeme
spring.data.elasticsearch.repositories.enabled=false

product.url=https://dummyjson.com/products/1
#product.url = https://dummyjson.com/products/999999999

#le27/04fichierLOG
logging.file.name=logs/app.log
logging.level.root=INFO